### ISSUE TITLE
Custom bad key checking

### ISSUE THREAD

**Issue by MarcoEscaleira** [MarceloSilva00/shouldYouDoIt_BE#6]
# Custom param key
 - Not detecting uppercases or lower cases

# Solution
 - Try to put it to lowercase and compare it then

**Comment by MarceloSilva00** [comment]
Fixed on commit :
https://github.com/MarceloSilva00/shouldYouDoIt_BE/commit/8bea089df10d797a2918232ba09980a7e9366a27
👍
